matrix:
  include:
    # Frontend
    - language: node_js
      node_js: 8.11.4
      before_install:
        - cd frontend/
      install: yarn
      script:
        - yarn run lint
        - yarn run tsc
    # Backend
    - language: python
      python: 3.6
      before_install:
        - cd backend/
        - cp .envexample .env
      install: pip install -r requirements/dev.txt
      script:
        - flask test
    # Contracts
    - language: node_js
      node_js: 8.11.4
      before_install:
        - cd contract/
      install: yarn && yarn add global truffle
      script:
        - yarn run test
